"""license header linter aspect for aspect_rules_lint framework"""

load("@aspect_rules_lint//lint:defs.bzl", "filter_srcs", "output_files", "should_visit")

_MNEMONIC = "AspectRulesLintLicenseHeader"

def _license_header_aspect_impl(target, ctx):
    if not should_visit(ctx.rule, ctx.attr._rule_kinds, ctx.attr._filegroup_tags):
        return []

    files_to_check = filter_srcs(ctx.rule)
    py_files = [f for f in files_to_check if f.extension == "py"]

    outputs, info = output_files(_MNEMONIC, target, ctx)

    if not py_files:
        # Using noop_lint_action(ctx, outputs) here results in an error since a conflicting
        # run_shell_0.sh file is generated by bazel/tools/lint_astrein.bzl
        ctx.actions.write(outputs.human.out, "")
        ctx.actions.write(outputs.machine.out, "")
        if outputs.human.exit_code:
            ctx.actions.write(outputs.human.exit_code, "0\n")
        if outputs.machine.exit_code:
            ctx.actions.write(outputs.machine.exit_code, "0\n")
        return [info]

    if outputs.human.exit_code and outputs.machine.exit_code:
        all_outputs = [
            outputs.human.out,
            outputs.machine.out,
            outputs.human.exit_code,
            outputs.machine.exit_code,
        ]
    else:
        all_outputs = [outputs.human.out, outputs.machine.out]

    license_header_runfiles = ctx.attr._checker[DefaultInfo].default_runfiles.files
    ctx.actions.run(
        inputs = depset(py_files, transitive = [license_header_runfiles]),
        outputs = all_outputs,
        executable = ctx.executable._checker,
        arguments = [
            outputs.human.out.path,
            outputs.machine.out.path,
            outputs.human.exit_code.path if outputs.human.exit_code else "",
            outputs.machine.exit_code.path if outputs.machine.exit_code else "",
        ] + [f.path for f in py_files],
        mnemonic = _MNEMONIC,
        progress_message = "Checking license headers for %{label}",
    )

    return [info]

def lint_license_header_aspect(
        binary,
        rule_kinds = ["py_binary", "py_library", "py_test"],
        filegroup_tags = ["python", "lint-with-license-header"]):
    return aspect(
        implementation = _license_header_aspect_impl,
        attr_aspects = ["deps"],
        attrs = {
            "_checker": attr.label(
                default = binary,
                executable = True,
                cfg = "exec",
            ),
            "_filegroup_tags": attr.string_list(default = filegroup_tags),
            "_options": attr.label(default = "@aspect_rules_lint//lint:options"),
            "_rule_kinds": attr.string_list(default = rule_kinds),
        },
    )
